Formatting

diff --git a/dockerfiles/Dockerfile.gosu b/dockerfiles/Dockerfile.gosu
--- a/dockerfiles/Dockerfile.gosu
+++ b/dockerfiles/Dockerfile.gosu
@@ -14,23 +14,23 @@
 #
 # SPDX-License-Identifier: Apache-2.0
 
-ARG UBI_VERSION=9
+ARG UBI_VERSION=10
 FROM registry.access.redhat.com/ubi${UBI_VERSION}/ubi-minimal:latest
 
-ENV GOSU_VERSION=1.17
+ENV GOSU_VERSION=1.19
 RUN microdnf update -y && \
     microdnf install -y wget && \
     microdnf clean all && rm -rf /var/cache/dnf
 RUN set -eux; \
     rpmArch="$(rpm --query --queryformat='%{ARCH}' rpm)"; \
     case "$rpmArch" in \
-        aarch64) dpkgArch='arm64' ;; \
-        armv[67]*) dpkgArch='armhf' ;; \
-        i[3456]86) dpkgArch='i386' ;; \
-        ppc64le) dpkgArch='ppc64el' ;; \
-        riscv64 | s390x) dpkgArch="$rpmArch" ;; \
-        x86_64) dpkgArch='amd64' ;; \
-        *) echo >&2 "error: unknown/unsupported architecture '$rpmArch'"; exit 1 ;; \
+    aarch64) dpkgArch='arm64' ;; \
+    armv[67]*) dpkgArch='armhf' ;; \
+    i[3456]86) dpkgArch='i386' ;; \
+    ppc64le) dpkgArch='ppc64el' ;; \
+    riscv64 | s390x) dpkgArch="$rpmArch" ;; \
+    x86_64) dpkgArch='amd64' ;; \
+    *) echo >&2 "error: unknown/unsupported architecture '$rpmArch'"; exit 1 ;; \
     esac; \
     wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/gosu-$dpkgArch"; \
     chmod +x /usr/local/bin/gosu && \
